### ISSUE TITLE
Size event fired during FakePlayer object construction causes crash

### ISSUE THREAD

**Issue by drwoops** [MinecraftForge/MinecraftForge#9659]
**Minecraft Version:**
1.20.1

**Forge Version:**
47.1.28

**Logs:** 
https://github.com/Creators-of-Create/Create/issues/5132

**Steps to Reproduce:**
 1. create 1.20.1 instance
 2. install forge
 3. install create
 4. try to place a deployer

**Description of issue:**
from what i can tell, there is a Size event during execution of the Deployer/FakePlayer constructor and this leads to a crash.  It does not happen with forge 47.1.4

**Comment by DBotThePony** [comment]
This is caused by breaking change introduced in https://github.com/MinecraftForge/MinecraftForge/commit/77fb08713ff6d0ce503e5d1677aec81e31ccb137, since crash report clearly state `java.lang.NoSuchMethodError: 'void net.minecraftforge.event.entity.EntityEvent$Size.setNewEyeHeight(float)'`, where `setNewEyeHeight` is clearly defined in `$EyeHeight` and not in `$Size`: https://github.com/MinecraftForge/MinecraftForge/blob/30d0a630d6fb81494132c49e476a8a7fc940d3a8/src/main/java/net/minecraftforge/event/entity/EntityEvent.java#L191

What to do in this case is up to Lex, but i would find it unfortunate to rollback changes introduced in commit above.

**Comment by LexManos** [comment]
https://github.com/MinecraftForge/MinecraftForge/commit/26adf4da44372df2819c6bbfeb179e02dd8acb14
