### ISSUE TITLE
[1.20.6] Forge fails to load brigadier classes in time for RegisterCommandsEvent leading to mod crashes

### ISSUE THREAD

**Issue by pop4959** [MinecraftForge/MinecraftForge#9986]
**Minecraft Version:** 1.20.6

**Forge Version:** forge-1.20.6-50.0.30

**Logs:** [crash-2024-05-24_06.21.58-client.txt](https://github.com/MinecraftForge/MinecraftForge/files/15428545/crash-2024-05-24_06.21.58-client.txt)
Relevant line: `java.lang.NoSuchMethodError: 'com.mojang.brigadier.builder.LiteralArgumentBuilder net.minecraft.commands.Commands.m_82127_(java.lang.String)'`

**Steps to Reproduce:**
 1. Use RegisterCommandsEvent to register a brigadier command
 2. Open the game

**Description of issue:** Class loading issue in Forge. Same command registration code worked in 1.20.4 and prior.

**Comment by LexManos** [comment]
Don't reobf your mod, and also this obviously shows the classes are loading fine. You're just calling the wrong function. Because you're reobfing your mod. There are no methods named `m_#####_` anymore.

**Comment by pop4959** [comment]
Ah... yeah I see, that's a big change from before. Didn't realize that we don't reobf anymore. Thank you for pointing that out, I've got it working now. I was so convinced that this was actually a bug and surprised no one was talking about it XD.
